First cut at adding IP-ID
richsalz/draft-ietf-uta-rfc6125bis pull request #54
Opened 2022-07-01 02:45 UTC by martinthomson

This wasn't as bad as I thought.  Though I did find some issues.  I'll
raise those separately.

Closes #53.

2022-07-01 13:55 UTC, richsalz commented
I remain opposed without WG consensus and re-doing the WGLC.

2022-07-05 15:50 UTC, richsalz commented
Consensus, as called by the chairs, is to not do this.

2022-08-16 17:37 UTC, stpeter requested changes

2022-08-16 17:37 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +that contains additionally supplementary information.  Supplementary information
```suggestion
that contains additional supplementary information.  Supplementary information
```

2022-08-16 17:37 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +An IP address is either a 4 byte IPv4 address {{!IPv4=RFC0791}} or a 16 byte
```suggestion
An IP address is either a 4-byte IPv4 address {{!IPv4=RFC0791}} or a 16-byte
```

2022-08-16 17:37 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +Each reference identifier in the list MUST be based on the input material and
We should define "input material" in the Terminology section. This might be slightly messy, because we can't very well use the term "source IP" as a parallel to "source domain" since "source IP" usually means something different (in connection-oriented protocols anyway)...

2022-08-16 17:37 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +through DNS resolution of those inputs.  This rule is important because
There isn't DNS resolution of an IP address in this context, is there?

2022-08-16 17:37 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +Using the combination of FQDN(s), IP address(es), and application service type, the client
```suggestion
Using the combination of FQDN(s) or IP address(es) plus optionally an application service type, the client
```

2022-08-16 17:37 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +* An IP-ID reference identifier MUST be exactly equal to the value of a
Do we want to say something like "bit-string equivalent" or at the end of the sentence "where equal means that the application performs octet-for-octet matching to test for bit-string identity"? (text borrowed from RFC 8264)

2022-08-16 17:37 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +An IP-ID matches based on comparing the bytes of the reference identity to the
See above on octet-by-octet matching, which might be a more precise formulation than "comparing the bytes".

2022-08-16 17:37 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +FQDN in some contexts.  If this can result in different security treatment and
I'm having trouble parsing this sentence. Perhaps "and if"?

2022-08-16 17:37 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
>  Jeff Hodges co-authored the previous version of these recommendations, {{VERIFY}}.
I suggest that we add something to the acknowledgements specifying that "Martin Thomson contributed the text about IP-IDs."

2022-08-17 05:53 UTC, martinthomson reviewed
Thanks Peter,

I've made some suggestions, but I'm not 100% on any of them.

2022-08-17 05:53 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +Each reference identifier in the list MUST be based on the input material and
Would this be better?

```suggestion
Each reference identifier in the list MUST be based on the user inputs and
```

2022-08-17 05:53 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +* An IP-ID reference identifier MUST be exactly equal to the value of a
```suggestion
* An IP-ID reference identifier MUST be exactly equal, octet for octet, to the value of a
```

2022-08-17 05:53 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +An IP-ID matches based on comparing the bytes of the reference identity to the
```suggestion
An IP-ID matches based on an octet-for-octet comparison of the bytes of the reference identity with the
```

2022-08-17 05:53 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +FQDN in some contexts.  If this can result in different security treatment and
```suggestion
FQDN in some contexts. This can result in different security treatment that might cause
```

...

2022-08-17 05:53 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +different components of a system classify the value differently, this might lead
```suggestion
different components of a system to classify the value differently, which might lead
```

2022-08-17 05:53 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
>  Jeff Hodges co-authored the previous version of these recommendations, {{VERIFY}}.
I'll leave that to you :)

2022-08-17 17:36 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
>  Jeff Hodges co-authored the previous version of these recommendations, {{VERIFY}}.
Yes, will do. :-)

2022-08-18 16:13 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +- IP-ID reference identifiers are added.
It'd be nice to include a pointer to RFC 9110 here.

2022-08-18 16:14 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +- IP-ID reference identifiers are added.
Something like "Extending work done in RFC 9110, added support for IP addresses in certificates via the IP-ID reference identifier type."

2022-08-19 00:38 UTC, martinthomson reviewed
Some suggestions for the change Peter talked about.  You'll want both.

2022-08-19 00:38 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +- IP-ID reference identifiers are added.
```suggestion
- IP-ID reference identifiers are added.  This builds on the definition in {{Section
  4.3.5 of HTTP}}.
```

Then you will need to add to the references...

2022-08-19 00:38 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
>    EMAIL-SRV: RFC6186
```suggestion
  EMAIL-SRV: RFC6186
  HTTP: RFC9110
```

2022-08-19 02:02 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
>  Jeff Hodges co-authored the previous version of these recommendations, {{VERIFY}}.
Done: https://github.com/richsalz/draft-ietf-uta-rfc6125bis/pull/62

2022-08-19 02:03 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +through DNS resolution of those inputs.  This rule is important because
Thoughts on a solution?

2022-08-19 02:40 UTC, martinthomson reviewed
This is the hard part because it hits a lot of the core concepts of the document.

I think that what this means is that we need to be more precise about the provenance of reference identifiers.  The current language in Section 6.1.1 is a bit wishy-washy.

2022-08-19 02:40 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +through DNS resolution of those inputs.  This rule is important because
I think that this is a bigger issue that this is just being exposed by this change.

The document talks about reference identifiers, but doesn't really go into much detail about how those are created.  I think that you already have much of what you need in Section 6.1.1.

Where it says:

> The client might need to extract the source domain and application service type from the input(s) it has received. 

You might instead say:

> This document doesn't precisely define how reference identifiers are derived.Applications that use this document need to define how reference identifiers are determined.  The security of a system that uses this document will depend on how reference identifiers are obtained.

Then back to the existing language:

> Naturally, if the inputs themselves are invalid or corrupt (e.g., a user has clicked a link provided by a malicious entity in a phishing attack), then the client might end up communicating with an unexpected application service.

Then for this text, we have a case where the system might handle an identifier that *looks* like a reference identifier, but it isn't.  What we're really saying here is:

> During the course of processing, a client might be exposed to identifiers that look like reference identifiers.  For example, DNS resolution that starts at a DNS-ID reference identifier might produce intermediate domain names that need to be further resolved.
>
> Any intermediate values are not reference identifiers and MUST NOT be treated as such, except as defined by the application.  In the DNS case, not treating intermediate domain names as reference identifiers removes DNS and DNS resolution from the attack surface.  An application might define a process for authenticating these intermediate identifiers in a way that then allows them to be used as a reference identifier; see for example {{?RFC8689}}.

2022-09-21 19:47 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +through DNS resolution of those inputs.  This rule is important because
Hi Martin, my apologies about the one-month delay in replying. Although much of your text seems fine, I suspect that this topic should be addressed in a separate issue/PR because, as you say, it was lurking all along and has merely been exposed by adding support for the IP-ID type.

2022-09-21 19:49 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +through DNS resolution of those inputs.  This rule is important because
Now see https://github.com/richsalz/draft-ietf-uta-rfc6125bis/issues/63

2022-09-21 20:20 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +through DNS resolution of those inputs.  This rule is important because
P.S. If the changes in this PR are acceptable to @richsalz then I suggest we merge it and deal with the reference identifier issue separately.

2022-09-21 20:21 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +through DNS resolution of those inputs.  This rule is important because
P.P.S. If this approach seems sensible, we can resolve this particular conversation before the merge. :-)

2022-09-21 20:36 UTC, richsalz reviewed
some nits.  looks fine.

2022-09-21 20:36 UTC, richsalz commented on draft-ietf-uta-rfc6125bis.md
> +and are included in PKIX certificates.
maybe: 'and that are included ...'

2022-09-21 20:36 UTC, richsalz commented on draft-ietf-uta-rfc6125bis.md
> +name (e.g., `example.com`), an IP address (IPv4 or IPv6), or is an identifier
s/is an identifier/or by an identifier/ ?

2022-09-21 20:36 UTC, richsalz commented on draft-ietf-uta-rfc6125bis.md
> +Using the combination of FQDN(s) or IP address(es) plus optionally an application service type, the client
comma before "plus optionally"

2022-09-29 02:52 UTC, martinthomson reviewed
Commenting with suggestions for Rich's suggestions.

2022-09-29 02:52 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +and are included in PKIX certificates.
```suggestion
and that are included in PKIX certificates.
```

2022-09-29 02:52 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +name (e.g., `example.com`), an IP address (IPv4 or IPv6), or is an identifier
```suggestion
name (e.g., `example.com`), an IP address (IPv4 or IPv6), or by an identifier
```

2022-09-29 02:52 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +Using the combination of FQDN(s) or IP address(es) plus optionally an application service type, the client
```suggestion
Using the combination of FQDN(s) or IP address(es), plus optionally an application service type, the client
```

2022-10-05 21:45 UTC, stpeter approved these changes

2022-10-05 21:47 UTC, stpeter commented
@richsalz I've approved this PR. If it meets with your approval too, would you mind merging it? Then we can work on issue 63 and submit a revised I-D before October 24.

2022-10-07 14:40 UTC, richsalz commented on draft-ietf-uta-rfc6125bis.md
> +* Identification beyond what the selected types of identities in the PKIX
Does this imply that all possible types are supported by this document? If so, then maybe append "that are discussed here"  If not, then ignore this.

2022-10-07 14:41 UTC, richsalz commented on draft-ietf-uta-rfc6125bis.md
> +A protocol can allow the use of an IP address in place of a DNS name.  This
s/can/may/

2022-10-07 14:42 UTC, richsalz commented on draft-ietf-uta-rfc6125bis.md
> +representation of an IPv4 address can appear to be a valid DNS name.  The two
s/appear to be/look like (but isn't)/

2022-10-07 14:43 UTC, richsalz commented
Overall looks fine.  I made a couple of nit-level suggestions.

2022-10-10 01:06 UTC, martinthomson reviewed
Attempts to address Rich's comments in suggestions.  And one small bit of push back.

2022-10-10 01:06 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +  certificate can express.
```suggestion
* Identification of servers using other than a domain name, IP address, or SRV service name.
```

I'm not really sure about this, but maybe this is probably more accurate.

2022-10-10 01:06 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +A protocol can allow the use of an IP address in place of a DNS name.  This
Do you mean "MAY" or "may"?  As this is not being permissive - this is merely a fact - I think that avoiding any implication of this being permissive is better.

2022-10-10 01:06 UTC, martinthomson commented on draft-ietf-uta-rfc6125bis.md
> +representation of an IPv4 address can appear to be a valid DNS name.  The two
```suggestion
representation of an IPv4 address can appear to be a valid DNS name, though it is not.  The two
```

2022-10-11 16:31 UTC, stpeter commented on draft-ietf-uta-rfc6125bis.md
> +A protocol can allow the use of an IP address in place of a DNS name.  This
Agreed, I prefer can to may here.

2022-10-11 17:23 UTC, stpeter commented
Merging this so that we can address issue 63 and submit a revised I-D.

2022-10-11 17:23 UTC, merged